name: Integration
on: [push]
jobs:
  Integration-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: ./node_modules/.bin/eslint . --ext .js
      - name: Run Unit Tests
        run: ./node_modules/.bin/jest
